### ISSUE TITLE
`data` folder missing from nom package

### ISSUE THREAD

**Issue by willfarrell** [esosedi/3166#5]
```bash
module.js:515
    throw err;
    ^

Error: Cannot find module '../data/iso3166-2.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/willfarrell/Development/github/react-intl-material/node_modules/iso3166-2-db/lib/defaultDataset.js:3:12)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

**Comment by theKashey** [comment]
Just yesterday I've released `package-self` to prevent issues like this. Too late :)

**Comment by theKashey** [comment]
Sorry, I was using `extracted` variant.
